### ISSUE TITLE
Error on importing namespace name in 1.6.0 version 

### ISSUE THREAD

**Issue by RodrigoBernardino** [henriqb/AdAuthenticator#5]
When I resolve the references for 1.6.0 version in vs2013 the imported namespace is 'hbehr.AdAuthentication'.
This namespace get error on build: 

The type or namespace name 'AdUser' could not be found (are you missing a using directive or an assembly reference?)

I tried to download the 1.5.1 version and the imported namespace was 'AdAuthentication' and this one worked.

**Comment by henriqb** [comment]
I think bug when creating nuget package.
Redeployed at 1.6.1 , with support for .net 4.0 , and new .net 4.7.
Try again
